### ISSUE TITLE
AzureTableAppender

### ISSUE THREAD

**Issue by mpgasser** [stemarie/log4net.Azure#48]
How can i "commit/flush" an entry immediately after logging it ?

Kind regrads
Markus

**Comment by bbarvish** [comment]
I am experiencing the same issue where the last log entry is not flushed and is only pushed out when a new  entry is logged.  Even after the app domain is shut down, it's not flushed.  

Any thoughts on improving this functionality to all entries are visible, even after a reasonable amount of time?

**Comment by bbarvish** [comment]
Since the AzureTableAppender derives from the BufferingAppenderSkelon, you can force SendBuffer to be called more frequently by adding the following config entry to your appender:

      <BufferSize value ="1"/>

This will likely degrade performance by some value, which will of course depend on logging frequency, but it will log immediately.

**Comment by jorupp** [comment]
If your issue is just to make sure entries get logged after a certain amount of time, I included logic that can do this in the Async appender I submitted as a PR: #54.

You could do it om a similar way with a subclass of the appender, adding a timer that calls this.Flush(false) on an interval - add a property to control the interval, and start it in an overload of ActivateOptions.

If you need to do it at a specific time, you could add a global event somewhere and use that to trigger the flush on all your (custom) appenders.
