### ISSUE TITLE
PartitionKey

### ISSUE THREAD

**Issue by baumerik** [stemarie/log4net.Azure#8]
Hi,

can you explain why you have used the LoggerName Property as PartitionKey?
most of the Logging examples always use a combination of year month day ...
And for Scaling in a table this make more sence or am I wrong?

regards,
Erik

**Comment by stemarie** [comment]
The Azure PartitionKey will eventually be used to split the Azure Table on possible separate partitions therefore enhancing performance - but this can only be the case if there are identical partition keys. The logger name made sense as it would allow the configuration of the log to group logs together which would not be possible using dates. I find using dates may group partitions together but since I don't see the primary purpose of querying the logs being the date but the part of the log/system and the date being secondary makes more sense.

Hope this helps,

**Comment by baumerik** [comment]
I know about this feature. but for performance issues (reading the logs) you need effective filters. and from my point of view the use case of logs is mostly search by time and then filter more detailed.
so look at: [Windows Azure Diagnostics!](http://gauravmantri.com/2012/02/17/effective-way-of-fetching-diagnostics-data-from-windows-azure-diagnostics-table-hint-use-partitionkey/)
Sometimes i heard about things like `long.MaxVlue-DateTime.UtcNow.Ticks` to get the latest items first.
And of course in my Projects mostly i have just one single Logger-Facade and so just one log4net logger. So i do not have Partition feature disabled.

So maybe i make an additional switch option to change the behavior.

Thanks for your explaination.
